version: 2.1
jobs:
  # Step1
  static-test:
    docker:
      - image: alpine:3.15
    steps:
      - run: echo "static test"
      - run: echo $MY_ENV_VAR
      - run: echo $MY_ENV_CONTEXT_KEY

  # Step2
  build:
    docker:
      # new image is
      # https://github.com/CircleCI-Public/cimg-go
      #- image: circleci/golang:1.17
      - image: cimg/go:1.17
    steps:
      - run: echo "hello world"
      - run: go version

  # Step3
  dynamic-test:
    docker:
      - image: alpine:3.15
    steps:
      - run: echo "dynamic test"

  # Step4
  deploy:
    docker:
      - image: alpine:3.15
    steps:
      - run: echo "deploy"

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - static-test:
          # type: approval
          context: MY_ENV_CONTEXT
          filters:
            branches:
              only: 
                - feature/seleniumize
      - build:
          requires:
            - static-test
          filters:
            branches:
              only: 
                - develop
      - dynamic-test:
          requires:
            - build
          filters:
            branches:
              only: 
                - develop
      - deploy:
          requires:
            - dynamic-test
          filters:
            branches:
              only: 
                - develop
