spring:
  datasource:
    url: jdbc:mysql://localhost:9999/employees?enabledTLSProtocols=TLSv1.2
    # url: jdbc:mysql://localhost:9999/demodb?enabledTLSProtocols=TLSv1.2
    username: demouser
    password: demopass
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      # SQL文を書いたスクリプトを実行する場合はalways
      mode: always
      # Spring Boot起動時に実行したいSQL文
      # 使わない場合はコメントアウト
      #schema-locations: classpath:mysql/schema.sql
      #data-locations: classpath:mysql/data.sql

