spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    job:
      enabled: true
      name: secondJob
    jdbc:
      initialize-schema: always
  autoconfigure:
    exclude: org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration

logging:
  level:
    root: "info"
    allinone: "debug"
  file:
    name: "mylog/myapplication-dev.log"
  group:
    allinone: "com.example.springbatchh2.allinone"
