spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  autoconfigure:
    exclude: org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration

logging:
  level:
    root: "info"
  file:
    name: "mylog/myapplication-dev.log"
