logging:
  level:
    root: "warn"
    springframework-web: "debug"
    hibernate: "error"
    tomcat: "info"
  # パッケージをグループ化してまとめて指定することもできる
  # keyにドットの指定を避けるためにグループ化でまとめる
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
    springframework-web: "org.springframework.web"
    hibernate: "org.hibernate"
  file:
    name: "mylog/myapplication-dev.log"

